apiVersion: v1
kind: Secret
metadata:
  name: kapture-auth
  namespace: kapture
type: Opaque
stringData:
  # Kredensial default untuk setup awal dashboard Kapture
  username: "admin"
  password: "admin123"
