apiVersion: v1
kind: Secret
metadata:
  name: k8s-log-catcher-auth
  namespace: log-catcher
type: Opaque
stringData:
  # Kredensial default untuk setup awal dashboard
  username: "admin"
  password: "admin123"
