apiVersion: v1
kind: Service
metadata:
  name: kapture
  namespace: kapture
  labels:
    app: kapture
spec:
  type: ClusterIP
  selector:
    app: kapture
    role: aggregator
  ports:
    - port: 19488
      targetPort: 19488
      name: dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: kapture-agents
  namespace: kapture
  labels:
    app: kapture
spec:
  clusterIP: None
  selector:
    app: kapture
    role: agent
  ports:
    - port: 19489
      targetPort: 19489
      name: http
