apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-rbac.yaml
  - 02-secret.yaml
  - 03-agent-daemonset.yaml
  - 04-aggregator-deployment.yaml
  - 05-service.yaml
