{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kapture.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kapture.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kapture.fullname" . }}
  labels:
    {{- include "kapture.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kapture.fullname" . }}
  labels:
    {{- include "kapture.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kapture.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kapture.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
